/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2019-03-05 00:44:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.sample;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class diary_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\" />\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("  <link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"resources/images/apple-icon.png\">\r\n");
      out.write("  <link rel=\"icon\" type=\"image/png\" href=\"resources/images/favicon.png\">\r\n");
      out.write("  <title>\r\n");
      out.write("    Black Dashboard by Creative Tim\r\n");
      out.write("  </title>\r\n");
      out.write("  <!--     Fonts and icons     -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"https://use.fontawesome.com/releases/v5.0.6/css/all.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Nucleo Icons -->\r\n");
      out.write("  <link href=\"resources/css/nucleo-icons.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <!-- CSS Files -->\r\n");
      out.write("  <link href=\"resources/css/black-dashboard.css?v=1.0.0\" rel=\"stylesheet\" />\r\n");
      out.write("  <!-- CSS Just for demo purpose, don't include it in your project -->\r\n");
      out.write("  <link href=\"resources/demo/demo.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <script>\r\n");
      out.write("function diaryWrite(){\r\n");
      out.write("\twindow.open('http://localhost:8888/project1/diaryWrite','',\r\n");
      out.write("\t\t\t'width=700, height=600, left=500, top=100' );\r\n");
      out.write("\t \r\n");
      out.write("  }\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"\">\r\n");
      out.write("  <div class=\"wrapper\">\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"sidebar-wrapper\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("          <a href=\"javascript:void(0)\" class=\"simple-text logo-mini\">\r\n");
      out.write("            CT\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"javascript:void(0)\" class=\"simple-text logo-normal\">\r\n");
      out.write("            Creative Tim\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"nav\">\r\n");
      out.write("         <li class=\"active \">\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"diary\">\r\n");
      out.write("              <i class=\"tim-icons icon-atom\"></i>\r\n");
      out.write("              <p>Diary</p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"dashboard\">\r\n");
      out.write("              <i class=\"tim-icons icon-chart-pie-36\"></i>\r\n");
      out.write("              <p>Dashboard</p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("         \r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"diaryMap\">\r\n");
      out.write("              <i class=\"tim-icons icon-pin\"></i>\r\n");
      out.write("              <p>Maps</p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"notification\">\r\n");
      out.write("              <i class=\"tim-icons icon-bell-55\"></i>\r\n");
      out.write("              <p>Notifications</p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"userProfile\">\r\n");
      out.write("              <i class=\"tim-icons icon-single-02\"></i>\r\n");
      out.write("              <p>User Profile</p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"language\">\r\n");
      out.write("              <i class=\"tim-icons icon-world\"></i>\r\n");
      out.write("              <p>Language</p>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main-panel\">\r\n");
      out.write("      <!-- Navbar -->\r\n");
      out.write("      <nav class=\"navbar navbar-expand-lg navbar-absolute navbar-transparent\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <div class=\"navbar-wrapper\">\r\n");
      out.write("            <div class=\"navbar-toggle d-inline\">\r\n");
      out.write("              <button type=\"button\" class=\"navbar-toggler\">\r\n");
      out.write("                <span class=\"navbar-toggler-bar bar1\"></span>\r\n");
      out.write("                <span class=\"navbar-toggler-bar bar2\"></span>\r\n");
      out.write("                <span class=\"navbar-toggler-bar bar3\"></span>\r\n");
      out.write("              </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"javascript:void(0)\">Icons</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navigation\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-bar navbar-kebab\"></span>\r\n");
      out.write("            <span class=\"navbar-toggler-bar navbar-kebab\"></span>\r\n");
      out.write("            <span class=\"navbar-toggler-bar navbar-kebab\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"navigation\">\r\n");
      out.write("            <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("              <li class=\"search-bar input-group\">\r\n");
      out.write("                <button class=\"btn btn-link\" id=\"search-button\" data-toggle=\"modal\" data-target=\"#searchModal\"><i class=\"tim-icons icon-zoom-split\"></i>\r\n");
      out.write("                  <span class=\"d-lg-none d-md-block\">Search</span>\r\n");
      out.write("                </button>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"dropdown nav-item\">\r\n");
      out.write("                <a href=\"javascript:void(0)\" class=\"dropdown-toggle nav-link\" data-toggle=\"dropdown\">\r\n");
      out.write("                  <div class=\"notification d-none d-lg-block d-xl-block\"></div>\r\n");
      out.write("                  <i class=\"tim-icons icon-sound-wave\"></i>\r\n");
      out.write("                  <p class=\"d-lg-none\">\r\n");
      out.write("                    Notifications\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"dropdown-menu dropdown-menu-right dropdown-navbar\">\r\n");
      out.write("                  <li class=\"nav-link\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-item dropdown-item\">Mike John responded to your email</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-link\">\r\n");
      out.write("                    <a href=\"javascript:void(0)\" class=\"nav-item dropdown-item\">You have 5 more tasks</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-link\">\r\n");
      out.write("                    <a href=\"javascript:void(0)\" class=\"nav-item dropdown-item\">Your friend Michael is in town</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-link\">\r\n");
      out.write("                    <a href=\"javascript:void(0)\" class=\"nav-item dropdown-item\">Another notification</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-link\">\r\n");
      out.write("                    <a href=\"javascript:void(0)\" class=\"nav-item dropdown-item\">Another one</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"dropdown nav-item\">\r\n");
      out.write("                <a href=\"#\" class=\"dropdown-toggle nav-link\" data-toggle=\"dropdown\">\r\n");
      out.write("                  <div class=\"photo\">\r\n");
      out.write("                    <img src=\"resources/images/anime3.png\" alt=\"Profile Photo\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <b class=\"caret d-none d-lg-block d-xl-block\"></b>\r\n");
      out.write("                  <p class=\"d-lg-none\">\r\n");
      out.write("                    Log out\r\n");
      out.write("                  </p>\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"dropdown-menu dropdown-navbar\">\r\n");
      out.write("                  <li class=\"nav-link\">\r\n");
      out.write("                    <a href=\"javascript:void(0)\" class=\"nav-item dropdown-item\">Profile</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"nav-link\">\r\n");
      out.write("                    <a href=\"javascript:void(0)\" class=\"nav-item dropdown-item\">Settings</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"dropdown-divider\"></li>\r\n");
      out.write("                  <li class=\"nav-link\">\r\n");
      out.write("                    <a href=\"javascript:void(0)\" class=\"nav-item dropdown-item\">Log out</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"separator d-lg-none\"></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("      <div class=\"modal modal-search fade\" id=\"searchModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"searchModal\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("          <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("              <input type=\"text\" class=\"form-control\" id=\"inlineFormInputGroup\" placeholder=\"SEARCH\">\r\n");
      out.write("              <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                <i class=\"tim-icons icon-simple-remove\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- End Navbar -->\r\n");
      out.write("      <div class=\"content\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col-md-12\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("              <div class=\"card-header\">\r\n");
      out.write("                <h3 class=\"title\">&nbsp&nbspDiary</h3>\r\n");
      out.write("             </div>\r\n");
      out.write("             \t<p>__님 오늘 어땠나요?<a href='javascript:void(0);'onclick=\"diaryWrite();\">일기작성</span><p>\r\n");
      out.write("          \r\n");
      out.write("           </div>\r\n");
      out.write("           \r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("             \r\n");
      out.write("      <footer class=\"footer\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("          <ul class=\"nav\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"javascript:void(0)\" class=\"nav-link\">\r\n");
      out.write("                Creative Tim\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"javascript:void(0)\" class=\"nav-link\">\r\n");
      out.write("                About Us\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a href=\"javascript:void(0)\" class=\"nav-link\">\r\n");
      out.write("                Blog\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <div class=\"copyright\">\r\n");
      out.write("            ©\r\n");
      out.write("            <script>\r\n");
      out.write("              document.write(new Date().getFullYear())\r\n");
      out.write("            </script> made with <i class=\"tim-icons icon-heart-2\"></i> by\r\n");
      out.write("            <a href=\"javascript:void(0)\" target=\"_blank\">Creative Tim</a> for a better web.\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"fixed-plugin\">\r\n");
      out.write("    <div class=\"dropdown show-dropdown\">\r\n");
      out.write("      <a href=\"#\" data-toggle=\"dropdown\">\r\n");
      out.write("        <i class=\"fa fa-cog fa-2x\"> </i>\r\n");
      out.write("      </a>\r\n");
      out.write("      <ul class=\"dropdown-menu\">\r\n");
      out.write("        <li class=\"header-title\"> Sidebar Background</li>\r\n");
      out.write("        <li class=\"adjustments-line\">\r\n");
      out.write("          <a href=\"javascript:void(0)\" class=\"switch-trigger background-color\">\r\n");
      out.write("            <div class=\"badge-colors text-center\">\r\n");
      out.write("              <span class=\"badge filter badge-primary active\" data-color=\"primary\"></span>\r\n");
      out.write("              <span class=\"badge filter badge-info\" data-color=\"blue\"></span>\r\n");
      out.write("              <span class=\"badge filter badge-success\" data-color=\"green\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"clearfix\"></div>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"adjustments-line text-center color-change\">\r\n");
      out.write("          <span class=\"color-label\">LIGHT MODE</span>\r\n");
      out.write("          <span class=\"badge light-badge mr-2\"></span>\r\n");
      out.write("          <span class=\"badge dark-badge ml-2\"></span>\r\n");
      out.write("          <span class=\"color-label\">DARK MODE</span>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"button-container\">\r\n");
      out.write("          <a href=\"https://www.creative-tim.com/product/black-dashboard\" target=\"_blank\" class=\"btn btn-primary btn-block btn-round\">Download Now</a>\r\n");
      out.write("          <a href=\"https://demos.creative-tim.com/black-dashboard/docs/1.0/getting-started/introduction.html\" target=\"_blank\" class=\"btn btn-default btn-block btn-round\">\r\n");
      out.write("            Documentation\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"header-title\">Thank you for 95 shares!</li>\r\n");
      out.write("        <li class=\"button-container text-center\">\r\n");
      out.write("          <button id=\"twitter\" class=\"btn btn-round btn-info\"><i class=\"fab fa-twitter\"></i> &middot; 45</button>\r\n");
      out.write("          <button id=\"facebook\" class=\"btn btn-round btn-info\"><i class=\"fab fa-facebook-f\"></i> &middot; 50</button>\r\n");
      out.write("          <br>\r\n");
      out.write("          <br>\r\n");
      out.write("          <a class=\"github-button\" href=\"https://github.com/creativetimofficial/black-dashboard\" data-icon=\"octicon-star\" data-size=\"large\" data-show-count=\"true\" aria-label=\"Star ntkme/github-buttons on GitHub\">Star</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!--   Core JS Files   -->\r\n");
      out.write("  <script src=\"resources/js/core/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/core/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/core/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"resources/js/plugins/perfect-scrollbar.jquery.min.js\"></script>\r\n");
      out.write("  <!--  Google Maps Plugin    -->\r\n");
      out.write("  <!-- Place this tag in your head or just before your close body tag. -->\r\n");
      out.write("  <script src=\"https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE\"></script>\r\n");
      out.write("  <!-- Chart JS -->\r\n");
      out.write("  <script src=\"resources/js/plugins/chartjs.min.js\"></script>\r\n");
      out.write("  <!--  Notifications Plugin    -->\r\n");
      out.write("  <script src=\"resources/js/plugins/bootstrap-notify.js\"></script>\r\n");
      out.write("  <!-- Control Center for Black Dashboard: parallax effects, scripts for the example pages etc -->\r\n");
      out.write("  <script src=\"resources/js/black-dashboard.min.js?v=1.0.0\"></script>\r\n");
      out.write("  <!-- Black Dashboard DEMO methods, don't include it in your project! -->\r\n");
      out.write("  <script src=\"resources/demo/demo.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("      $().ready(function() {\r\n");
      out.write("        $sidebar = $('.sidebar');\r\n");
      out.write("        $navbar = $('.navbar');\r\n");
      out.write("        $main_panel = $('.main-panel');\r\n");
      out.write("\r\n");
      out.write("        $full_page = $('.full-page');\r\n");
      out.write("\r\n");
      out.write("        $sidebar_responsive = $('body > .navbar-collapse');\r\n");
      out.write("        sidebar_mini_active = true;\r\n");
      out.write("        white_color = false;\r\n");
      out.write("\r\n");
      out.write("        window_width = $(window).width();\r\n");
      out.write("\r\n");
      out.write("        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        $('.fixed-plugin a').click(function(event) {\r\n");
      out.write("          if ($(this).hasClass('switch-trigger')) {\r\n");
      out.write("            if (event.stopPropagation) {\r\n");
      out.write("              event.stopPropagation();\r\n");
      out.write("            } else if (window.event) {\r\n");
      out.write("              window.event.cancelBubble = true;\r\n");
      out.write("            }\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('.fixed-plugin .background-color span').click(function() {\r\n");
      out.write("          $(this).siblings().removeClass('active');\r\n");
      out.write("          $(this).addClass('active');\r\n");
      out.write("\r\n");
      out.write("          var new_color = $(this).data('color');\r\n");
      out.write("\r\n");
      out.write("          if ($sidebar.length != 0) {\r\n");
      out.write("            $sidebar.attr('data', new_color);\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          if ($main_panel.length != 0) {\r\n");
      out.write("            $main_panel.attr('data', new_color);\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          if ($full_page.length != 0) {\r\n");
      out.write("            $full_page.attr('filter-color', new_color);\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          if ($sidebar_responsive.length != 0) {\r\n");
      out.write("            $sidebar_responsive.attr('data', new_color);\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('.switch-sidebar-mini input').on(\"switchChange.bootstrapSwitch\", function() {\r\n");
      out.write("          var $btn = $(this);\r\n");
      out.write("\r\n");
      out.write("          if (sidebar_mini_active == true) {\r\n");
      out.write("            $('body').removeClass('sidebar-mini');\r\n");
      out.write("            sidebar_mini_active = false;\r\n");
      out.write("            blackDashboard.showSidebarMessage('Sidebar mini deactivated...');\r\n");
      out.write("          } else {\r\n");
      out.write("            $('body').addClass('sidebar-mini');\r\n");
      out.write("            sidebar_mini_active = true;\r\n");
      out.write("            blackDashboard.showSidebarMessage('Sidebar mini activated...');\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("          // we simulate the window Resize so the charts will get updated in realtime.\r\n");
      out.write("          var simulateWindowResize = setInterval(function() {\r\n");
      out.write("            window.dispatchEvent(new Event('resize'));\r\n");
      out.write("          }, 180);\r\n");
      out.write("\r\n");
      out.write("          // we stop the simulation of Window Resize after the animations are completed\r\n");
      out.write("          setTimeout(function() {\r\n");
      out.write("            clearInterval(simulateWindowResize);\r\n");
      out.write("          }, 1000);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('.switch-change-color input').on(\"switchChange.bootstrapSwitch\", function() {\r\n");
      out.write("          var $btn = $(this);\r\n");
      out.write("\r\n");
      out.write("          if (white_color == true) {\r\n");
      out.write("\r\n");
      out.write("            $('body').addClass('change-background');\r\n");
      out.write("            setTimeout(function() {\r\n");
      out.write("              $('body').removeClass('change-background');\r\n");
      out.write("              $('body').removeClass('white-content');\r\n");
      out.write("            }, 900);\r\n");
      out.write("            white_color = false;\r\n");
      out.write("          } else {\r\n");
      out.write("\r\n");
      out.write("            $('body').addClass('change-background');\r\n");
      out.write("            setTimeout(function() {\r\n");
      out.write("              $('body').removeClass('change-background');\r\n");
      out.write("              $('body').addClass('white-content');\r\n");
      out.write("            }, 900);\r\n");
      out.write("\r\n");
      out.write("            white_color = true;\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('.light-badge').click(function() {\r\n");
      out.write("          $('body').addClass('white-content');\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('.dark-badge').click(function() {\r\n");
      out.write("          $('body').removeClass('white-content');\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
